apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  type: NodePort # Change to LoadBalancer for cloud environments
  ports:
  - port: 6379
    nodePort: 30001 # Optional for NodePort
  selector:
    app: redis
