apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
  namespace: default
spec:
  serviceName: redis-cluster-service
  replicas: 9
  selector:
    matchLabels:
      app: redis-cluster
  template:
    metadata:
      labels:
        app: redis-cluster
        name: redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: default #redis-namespace
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: client
  selector:
    app: redis-cluster
